/* Pipeline to deploy Hyperledger Fabric to single cluster Test environment
// This pipeline does the following
//  1. creates the specific network.yaml from the sample by replacing keys with values
//  2. Sets up ansible environment and kubernetes environment
//  3. Deploys Fabric node till peers
//  4. Creates one channel and joins channel
*/
pipeline {
    agent {
        label 'ansible' // use an ansible based agent
    }
    
    environment {
        //Define common variables
        //GIT repo links
        GITOPS_REPO="innersource.accenture.com/scm/blockofz/blockchain-automation-framework.git"
        //SSH version is also needed
        GITOPS_SSH="ssh://git@innersource.accenture.com/blockofz/blockchain-automation-framework.git"
        //Release path for Fabric
        REL_PATH="platforms/hyperledger-fabric/releases/dev"
        //Path for charts that will be deployed
        CHART_PATH="platforms/hyperledger-fabric/charts"
        //Service User credentials from Jenkins used to check-in to git
        GIT_CREDS="blockofz_serviceuser"
        //Store root directory
        ROOT_DIR="${pwd()}"
        //Docker registry address
        DOCKER_REGISTRY = "adopblockchaincloud0502.azurecr.io"		    
        //username for docker registry 
        DOCKER_USERNAME = 'ADOPBlockchainCloud0502'
        //password for docker registry taken from Jenkins credentials
        DOCKER_PASSWORD = credentials('azure_container_password')

        //KUBECONFIG file to connect to the single cluster. This file is replace when pipeline runs
        // by the choice you make in the build/input parameters
        KUBECONFIG="${pwd()}/platforms/hyperledger-fabric/configuration/kubeconfig.yaml"

    }

    parameters {
        string(defaultValue: "http://aa6305c6592c511e9aaab02f438592f4-1279856826.eu-west-2.elb.amazonaws.com:8200", description: 'Vault Server address?', name: 'VAULT_ADDR')
        password(defaultValue: "", description: 'Vault root token?', name: 'VAULT_TOKEN')
        choice(choices: 'Yes\nNo', description: 'New Release?', name: 'RELEASE_NEW')
        string(defaultValue: "feature/BLOCKOFZ-590-Testing-of-Helm-Charts-for-Corda-using-Helm-Unit-Test", description: 'GitOps Release Branch', name: 'RELEASE_BRANCH')
        string(defaultValue: 'deploy-infra-aws-org3', description: 'Which job to get Kubeconfig from?', name: 'KUBE_PROJECT')
        string(defaultValue: 'kube_user.yaml', description: 'Which Kubeconfig filename to use?', name: 'KUBE_FILE')
        string(defaultValue: 'fabric-org3-cluster', description: 'Cluster name?', name: 'CLUSTER_CONTEXT')
        string(defaultValue: 'eu-west-1', description: 'AWS Region?', name: 'REGION')
        choice(choices: 'No\nYes', description: 'Delete All Existing Network?', name: 'RESET_ACTION')
    }

    stages {
		/*
		 *  Fetching the kube config file from the cluster creation pipeline
		 *  "KUBE_PROJECT" variable contains the cluster creation pipeline name
		 *  "selector" variable determines the last successful build of cluster creation
		 *  "target" variable defines the location of the cluster configuration file path in Jenkins VM
		 */
        stage('Get K8 configs from terraform job') {
            steps {
                copyArtifacts filter: 'kubernetes/*', fingerprintArtifacts: true, projectName: "${params.KUBE_PROJECT}", selector: lastSuccessful(), target: 'platforms/hyperledger-fabric/configuration'
                sh """
					 ls -lat platforms/hyperledger-fabric/configuration/kubernetes
                     cp platforms/hyperledger-fabric/configuration/kubernetes/${params.KUBE_FILE} ${KUBECONFIG}
                """
            }
        }

		/*
		 *  Create the Fabric configuration file
		 */
        stage('Create Fabric Configuration') {
            steps {
                //WithCredentials to get the username and password for GIT user
                withCredentials([
                     usernamePassword(credentialsId: "${GIT_CREDS}", 
                     usernameVariable: 'USERNAME', 
                     passwordVariable: 'PASSWORD'
                )]) {
                    script {
                        //encode the username and password
                        env.encodedGitName=URLEncoder.encode(USERNAME, "UTF-8")
                        env.encodedGitPass=URLEncoder.encode(PASSWORD, "UTF-8")
                    }
                    // Replace the sample fabric network.yaml and fill in required parameters
                    dir('platforms/hyperledger-fabric/configuration/') {
                        sh """
                            cp samples/network-fabricv2.yaml network.yaml
                            sed -i -e 's*docker_url*${DOCKER_REGISTRY}*g' network.yaml
                            sed -i -e 's*docker_username*${DOCKER_USERNAME}*g' network.yaml
                            sed -i -e 's*docker_password*${DOCKER_PASSWORD}*g' network.yaml
                            sed -i -e 's*vault_addr*${params.VAULT_ADDR}*g' network.yaml
                            sed -i -e 's*vault_root_token*${params.VAULT_TOKEN}*g' network.yaml                            
                            sed -i -e 's*gitops_ssh_url*${GITOPS_SSH}*g' network.yaml                            
                            sed -i -e 's*gitops_branch*${params.RELEASE_BRANCH}*g' network.yaml
                            sed -i -e 's*gitops_release_dir*${REL_PATH}*g' network.yaml
                            sed -i -e 's*gitops_charts*${CHART_PATH}*g' network.yaml
                            sed -i -e 's*gitops_push_url*${GITOPS_REPO}*g' network.yaml
                            sed -i -e 's*git_username*${USERNAME}*g' network.yaml
                            sed -i -e 's+git_password+${PASSWORD}+g' network.yaml
                            sed -i -e 's*cluster_region*${params.REGION}*g' network.yaml
                            sed -i -e 's*cluster_context*${params.CLUSTER_CONTEXT}*g' network.yaml
                            sed -i -e 's*cluster_config*${KUBECONFIG}*g' network.yaml
                        """
                    }
                }
            }
        }
        stage('Add AWS Details to Configuration') {
            steps {
                //WithCredentials to get the username and password for AWS Account
                //TODO: Use when statement when multiple cloud provider is available
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'terraform_user',
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    // Add AWS specific parameters
                    dir('platforms/hyperledger-fabric/configuration/') {
                        sh """
                            sed -i -e 's+aws_access_key+${AWS_ACCESS_KEY_ID}+g' network.yaml
                            sed -i -e 's+aws_secret_key+${AWS_SECRET_ACCESS_KEY}+g' network.yaml                           
                        """
                    }
                }
            }
        }
        /*
		 *  If RESET_ACTION is yes, delete the network
         *  NOTE: The Flux installation is also deleted, so you have to provide write access to FLUX SSH KEY Again
		 */
        stage('Reset existing network') {
            when {
                expression {
                    params.RESET_ACTION.toLowerCase() == 'yes'
                }
            }
            steps {
                 dir('platforms/hyperledger-fabric/configuration/') {
                    echo 'Run ansible playbook'
                    sh 'ansible-playbook reset-network.yaml -e "@./network.yaml"'
                }
            }    
        }
        /*
		 *  Execute site.yaml which will setup environment and deploy the network
         *  NOTE: Please copy the FLUX SSH KEY generated and provide read-write access to this key on the git repo
		 */
        stage('Deploy Fabric Network and create channel') {
            steps {
                dir('platforms/hyperledger-fabric/configuration/') {
                    sh """
                        ansible-playbook ../../shared/configuration/site.yaml -e "@./network.yaml"
                    """
                }
            }
        }
    }
}